# Generated by Django 5.1.1 on 2024-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='image',
            field=models.ImageField(null=True, upload_to='???'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
