# Generated by Django 5.1.1 on 2024-10-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airport', '0002_alter_airplanetype_options_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seats_in_row',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_rows',
            field=models.IntegerField(default=30),
        ),
    ]
